server:
  port: 8080
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: "jdbc:mysql://localhost:3306/text?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
      max-active: 10